# /tmp/db-ambassador-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-ambassador-config
data:
  haproxy.cfg: |
    global
      daemon
      maxconn 256

    defaults
      mode tcp
      timeout connect 10s
      timeout client 1m
      timeout server 1m

    frontend postgres_frontend
      bind *:5432
      default_backend postgres_backend

    backend postgres_backend
      server external-db external-db.example.com:5432
