{{- if .Values.userService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-user-service
  labels:
    {{- include "ecommerce.microserviceLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "user-service") | nindent 4 }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ecommerce.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: user-service
{{- end }}
